"""empty message

Revision ID: 1610f43b80cd
Revises: 876809bab0d6
Create Date: 2024-10-20 23:14:27.747646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1610f43b80cd'
down_revision = '876809bab0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('issue_date',
               existing_type=sa.DATE(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('return_date',
               existing_type=sa.DATE(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=sa.Float(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('issue_date',
               existing_type=sa.Float(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
